import type { Metadata } from 'next';
import type { ReactNode } from 'react';
// 1. Import Tajawal alongside your other fonts
import { Geist, Geist_Mono } from 'next/font/google';
import { Tajawal,Inter,Poppins } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import Script from 'next/script';
import { GoogleAnalytics } from '@next/third-parties/google';



const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// 2. Configure the Arabic font (Tajawal)
const tajawal = Tajawal({
  variable: '--font-tajawal',
  subsets: ['arabic'],
  weight: ['400', '500', '700', '800'], // Added weights for header, body, and hero
});
const inter = Inter({
  variable: '--font-Inter',
  subsets: ['latin'],
  weight: ['400', '500', '700', '800'], // Added weights for header, body, and hero
});
const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '700', '800'], // Added weights for header, body, and hero
});


export const metadata: Metadata = {
  title: 'بيكسلات | Pexlat', // Updated title
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    // 3. Set lang="ar" (Arabic) and dir="rtl" (Right-to-Left)
    <html lang="ar" dir="rtl" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tajawal.variable} antialiased`}
      >
        <Script id="tiktok-pixel" strategy="afterInteractive">
          {`
            !function (w, d, t) { 
             w.TiktokAnalyticsObject=t;var ttq=w[t]=w[t]||[];ttq.methods=["page","track","identify","instances","debug","on","off","once","ready","alias","group","enableCookie","disableCookie"],ttq.setAndDefer=function(t,e){t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var i=0;i<ttq.methods.length;i++)ttq.setAndDefer(ttq,ttq.methods[i]);ttq.instance=function(t){for(var e=ttq.methods[i=0];i<ttq.methods.length;i++)ttq.setAndDefer(t,e);return t};ttq.load=function(e,n){var i="https://analytics.tiktok.com/i18n/pixel/events.js";ttq._i=ttq._i||{},ttq._i[e]=[],ttq._i[e]._u=i,ttq._t=ttq._t||{},ttq._t[e]=+new Date,ttq._o=ttq._o||{},ttq._o[e]=n||{};var o=document.createElement("script");o.type="text/javascript",o.async=!0,o.src=i+"?sdkid="+e+"&lib="+t;var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(o,a)};
             
             ttq.load('D1JG87RC77U77R4VV51G'); 
              ttq.page();
            }(window, document, 'ttq');
          `}
        </Script>
        <ThemeProvider attribute='class' enableSystem >
          {children}
        </ThemeProvider> 
        
      </body>
      <GoogleAnalytics gaId="G-KD4WF4VZM6" />
    </html>
  );
}