import type { Metadata } from 'next';
import type { ReactNode } from 'react';
// 1. Import Tajawal alongside your other fonts
import { Geist, Geist_Mono } from 'next/font/google';
import { Tajawal,Inter,Poppins } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// 2. Configure the Arabic font (Tajawal)
const tajawal = Tajawal({
  variable: '--font-tajawal',
  subsets: ['arabic'],
  weight: ['400', '500', '700', '800'], // Added weights for header, body, and hero
});
const inter = Inter({
  variable: '--font-Inter',
  subsets: ['latin'],
  weight: ['400', '500', '700', '800'], // Added weights for header, body, and hero
});
const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '700', '800'], // Added weights for header, body, and hero
});


export const metadata: Metadata = {
  title: 'بيكسلات | Pexlat', // Updated title
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    // 3. Set lang="ar" (Arabic) and dir="rtl" (Right-to-Left)
    <html lang="ar" dir="rtl" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tajawal.variable} antialiased`}
      >
        <ThemeProvider attribute='class' enableSystem >
          {children}
        </ThemeProvider> 
        
      </body>
    </html>
  );
}